const ApplicationsData = [
  {id: 0, name: 'Quintin Ed', description: 'Love Coding in Java', registered: '2018/01/01', role: 'Developer', status: 'New'},
  {id: 1, name: 'Samppa Nori', description: 'Java Developer, passionate about Vuejs', registered: '2018/01/01', role: 'Developer', status: 'New'},
  {id: 2, name: 'Estavan Lykos', description: 'Enjoy Coding in Java', registered: '2018/02/01', role: 'Developer', status: 'New'},
  {id: 3, name: 'Chetan Mohamed', description: 'Freelance Java Developer', registered: '2018/02/01', role: 'Developer', status: 'New'},
  {id: 4, name: 'Derick Maximinus', description: 'Java Developer from NCS', registered: '2018/03/01', role: 'Developer', status: 'New'},
  {id: 5, name: 'Friderik Dávid', description: 'Developed 5 web apps with Java', registered: '2018/01/21', role: 'Developer', status: 'New'},
  {id: 6, name: 'Yiorgos Avraamu', description: 'JavaEE experiences and still going strong', registered: '2018/01/01', role: 'Developer', status: 'Invited'},
  {id: 7, name: 'Avram Tarasios', description: 'JavaEE experiences and still going strong', registered: '2018/02/01', role: 'Developer', status: 'Invited'},
  {id: 8, name: 'Quintin Ed', description: 'JavaEE experiences and still going strong', registered: '2018/02/01', role: 'Developer', status: 'Invited'},
  {id: 9, name: 'Enéas Kwadwo', description: 'JavaEE experiences and still going strong', registered: '2018/03/01', role: 'Developer', status: 'Reviewed'},
  {id: 10, name: 'Agapetus Tadeáš', description: 'JavaEE experiences and still going strong', registered: '2018/01/21', role: 'Developer', status: 'Reviewed'},
  {id: 11, name: 'Carwyn Fachtna', description: 'JavaEE experiences and still going strong', registered: '2018/01/01', role: 'Developer', status: 'Reviewed'},
  {id: 12, name: 'Nehemiah Tatius', description: 'JavaEE experiences and still going strong', registered: '2018/02/01', role: 'Developer', status: 'Reviewed'},
  {id: 13, name: 'Ebbe Gemariah', description: 'JavaEE experiences and still going strong', registered: '2018/02/01', role: 'Developer', status: 'Reviewed'},
  {id: 14, name: 'Eustorgios Amulius', description: 'JavaEE experiences and still going strong', registered: '2018/03/01', role: 'Developer', status: 'Reviewed'},
  {id: 15, name: 'Leopold Gáspár', description: 'JavaEE experiences and still going strong', registered: '2018/01/21', role: 'Developer', status: 'Reviewed'},
  {id: 16, name: 'Pompeius René', description: 'JavaEE experiences and still going strong', registered: '2018/01/01', role: 'Developer', status: 'Reviewed'},
  {id: 17, name: 'Paĉjo Jadon', description: 'JavaEE experiences and still going strong', registered: '2018/02/01', role: 'Developer', status: 'Reviewed'},
  {id: 18, name: 'Micheal Mercurius', description: 'JavaEE experiences and still going strong', registered: '2018/02/01', role: 'Developer', status: 'Reviewed'},
  {id: 19, name: 'Ganesha Dubhghall', description: 'JavaEE experiences and still going strong', registered: '2018/03/01', role: 'Developer', status: 'Reviewed'},
  {id: 20, name: 'Hiroto Šimun', description: 'JavaEE experiences and still going strong', registered: '2018/01/21', role: 'Developer', status: 'Reviewed'},
  {id: 21, name: 'Vishnu Serghei', description: 'JavaEE experiences and still going strong', registered: '2018/01/01', role: 'Developer', status: 'Reviewed'},
  {id: 22, name: 'Zbyněk Phoibos', description: 'JavaEE experiences and still going strong', registered: '2018/02/01', role: 'Developer', status: 'Reviewed'},
  {id: 23, name: 'Einar Randall', description: 'JavaEE experiences and still going strong', registered: '2018/02/01', role: 'Developer', status: 'Rejected'},
  {id: 24, name: 'Félix Troels', description: 'JavaEE experiences and still going strong', registered: '2018/03/21', role: 'Developer', status: 'Rejected'},
  {id: 25, name: 'Aulus Agmundr', description: 'JavaEE experiences and still going strong', registered: '2018/01/01', role: 'Developer', status: 'Rejected'},
  {id: 42, name: 'Ford Prefex', description: 'JavaEE experiences and still going strong', registered: '2001/05/21', role: 'Developer', status: 'Rejected'}
]

export default ApplicationsData
